// @ts-ignore
import JSZip from "jszip";
import { saveAs } from "file-saver";
import { fetchAllReportData } from "./reportData";
import { generateExcelReport } from "./generateExcel";
import { generatePDFReport } from "./generatePDF";

interface ReportParams {
  restaurantName: string;
  branchName: string;
  from: string;
  to: string;
  restaurantId: number;
  branchId: number;
  token: string;
  apiUrl: string;
}

export async function generateAndDownloadFullReport(params: ReportParams): Promise<void> {
  const meta = {
    restaurantName: params.restaurantName,
    branchName: params.branchName,
    from: params.from,
    to: params.to,
  };

  // Step 1: Fetch all data
  const data = await fetchAllReportData({
    restaurantId: params.restaurantId,
    branchId: params.branchId,
    from: params.from,
    to: params.to,
    token: params.token,
    apiUrl: params.apiUrl,
  });

  // Step 2: Generate Excel and PDF in parallel
  const [excelBuffer, pdfBuffer] = await Promise.all([
    generateExcelReport(data, meta),
    generatePDFReport(data, meta),
  ]);

  // Step 3: Bundle into a ZIP
  const zip = new JSZip();
  const branchSlug = params.branchName.replace(/\s+/g, "-");
  const dateSlug = `${params.from}_to_${params.to}`;
  const folderName = `DineInk-Report-${branchSlug}-${dateSlug}`;

  const folder = zip.folder(folderName)!;
  folder.file(
    `${folderName}-DATA.xlsx`,
    excelBuffer,
    { binary: true },
  );
  folder.file(
    `${folderName}-REPORT.pdf`,
    pdfBuffer,
    { binary: true },
  );

  // Step 4: Add a README
  folder.file("README.txt", `DineInk Full Business Report
==============================

Restaurant : ${params.restaurantName}
Branch     : ${params.branchName}
Period     : ${params.from}  →  ${params.to}
Generated  : ${new Date().toLocaleString("en-IN")}

FILES IN THIS PACKAGE
─────────────────────
1. ${folderName}-REPORT.pdf
   Premium PDF report with charts and visual analytics.
   Open with any PDF reader.

2. ${folderName}-DATA.xlsx
   Complete Excel workbook with 12 data sheets:
   Cover, Executive Summary, Revenue & Orders, Top Items,
   All Bills, Customers, Expenses, Kitchen Analytics,
   Attendance, Cash Sessions, Branch Comparison, Forecast.
   Open with Excel, Google Sheets, or LibreOffice.

Generated by DineInk Restaurant Intelligence Platform
`);

  // Step 5: Download the ZIP
  const zipBlob = await zip.generateAsync({ type: "blob", compression: "DEFLATE", compressionOptions: { level: 6 } });
  saveAs(zipBlob, `${folderName}.zip`);
}
